# Generated by Django 4.0.2 on 2023-02-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(default=None, max_length=32, null=True)),
                ('company', models.CharField(default=None, max_length=64, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('delivery_address', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('note', models.TextField(default=None, null=True)),
                ('goods', models.CharField(default=None, max_length=256, null=True)),
                ('income', models.PositiveIntegerField(default=None, help_text='The total amount to be paid by the buyer', null=True)),
                ('goods_cost', models.PositiveIntegerField(default=None, help_text='The cost of goods (not including shipping)', null=True)),
                ('loading_cost', models.PositiveIntegerField(default=None, help_text='The cost of transferring the goods to delivery', null=True)),
                ('delivery_cost', models.PositiveIntegerField(default=None, null=True)),
                ('other_expenses', models.IntegerField(default=None, help_text='Other expenses (not including the cost of goods and delivery)', null=True)),
                ('tax', models.PositiveIntegerField(default=None, help_text='The amount of money to be paid in taxes', null=True)),
                ('delivery_date', models.DateTimeField(default=None, null=True)),
                ('delivery_address', models.CharField(default=None, max_length=256, null=True)),
                ('loading_address', models.CharField(default=None, help_text='The place where the product will be handed over for delivery', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='crm.person')),
                ('list', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.deallist')),
            ],
        ),
    ]
