# Generated by Django 4.0.2 on 2023-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='deal',
            name='order',
            field=models.IntegerField(default=0, help_text='Sorting is done by this field'),
        ),
    ]
